spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: test1
        uri:
          http://localhost:3001/
        predicates:
        - Path=/test1/**
      - id: test2
        uri:
          http://localhost:3002/
        predicates:
        - Path=/test2/**    
server:
  port: 4000
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
      